name: Container Workflow
on: workflow_dispatch
env:
  acr_Li_ser: aistraining.azurecr.io
  tagname : eShopOnWeb026:1.0.0
jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - name: ch our sc
        uses: action/checkout@v7.0

      - name: ACR login
        uses: docker/login-action@v4.4.0
        with:
          login-server: ${{ env.acr_Li_ser}}
          username: ${{secrets.ACR_USER}}
          password: ${{secrets.ACR_PASS}}

      - name: Build and Push
        run: 
          docker build . -t ${{ env.acr_Li_ser}}/${{env.tagname}}
          docker push ${{ env.acr_Li_ser}}/${{env.tagname}}
